apiVersion: apps/v1
kind: Deployment
metadata:
  name: vp-deployment
  labels:
    app: my-deployment
    env: dev
  namespace: devnamespace
  annotations:
    myecrimage: 487985088364.dkr.ecr.ap-south-1.amazonaws.com/developer
spec:
  replicas: 4
  minReadySeconds: 6
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: 487985088364.dkr.ecr.ap-south-1.amazonaws.com/developer:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /nandini
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            exec:
              command: ["echo", "hii"]
          resources:
            requests:
              cpu: "250m"
              memory: "300Mi"
            limits:
              cpu: "250m"
              memory: "300Mi"
